site_name: My MkDocs Site
docs_dir: docs  # Directory containing your source documentation files
site_dir: site  # Directory where the generated HTML site will be placed

nav:
  - Home: index.md
  - Tutorial: mpi.md
        #- About: about.md
        #  # Add more navigation items as needed
        #
theme:
  name: material #readthedocs 
  features:
    - content.tabs.link
  
  palette:

  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
    primary: indigo

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo


    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
    primary: indigo
  
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  font:
    text: Mukta
    code: Roboto Mono

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
        #
plugins:
  - search
        #        # Add more plugins as needed
